name: location_picker_fluttify
description: A Location Picker. Based on `amap_x_fluttify` Plugins.
version: 0.0.1
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/location_picker_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_map_fluttify: ^0.8.4+edd4090
  amap_search_fluttify: ^0.3.3+97873c8
  permission_handler: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.location_picker_fluttify
    pluginClass: LocationPickerFluttifyPlugin