name: location_picker_fluttify
description: A Location Picker. Based on `amap_x_fluttify` Plugins.
version: 0.0.3
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/location_picker_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_map_fluttify: ^0.14.2+e26c0fa
  amap_search_fluttify: ^0.5.0+acdcd89
  permission_handler: ^4.0.0
  rxdart: ^0.23.1
  after_layout: ^1.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  plugin:
    androidPackage: me.yohom.location_picker_fluttify
    pluginClass: LocationPickerFluttifyPlugin
  assets:
    - images/